/**
 * Kart Repository Integration Tests
 * Feature: 004-maintenance-core
 * 
 * Integration tests for Firestore Kart CRUD operations
 * NOTE: These tests require Firebase emulator to be running
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
    getKarts,
    getKart,
    createKart,
    updateKart,
    deleteKart
} from '@/lib/firestore/karts';
import { createSessionLog } from '@/lib/firestore/sessionLogs';
import { createTask } from '@/lib/firestore/tasks';
import { createShoppingItem } from '@/lib/firestore/shoppingList';

describe('Kart Repository Integration Tests', () => {
    let createdKartIds: string[] = [];

    afterEach(async () => {
        // Cleanup: Delete all created karts
        for (const kartId of createdKartIds) {
            try {
                await deleteKart(kartId);
            } catch {
                // Kart may already be deleted in test
            }
        }
        createdKartIds = [];
    });

    describe('createKart', () => {
        it('should create kart with default thresholds', async () => {
            const kart = await createKart('Kart #17');
            createdKartIds.push(kart.id);

            expect(kart.id).toBeDefined();
            expect(kart.name).toBe('Kart #17');
            expect(kart.totalEngineHours).toBe(0);
            expect(kart.thresholds.length).toBeGreaterThan(0);
            expect(kart.thresholds[0].type).toBe('Oil Change');
        });
    });

    describe('getKarts', () => {
        it('should return all karts for current user', async () => {
            const kart1 = await createKart('Kart #1');
            const kart2 = await createKart('Kart #2');
            createdKartIds.push(kart1.id, kart2.id);

            const karts = await getKarts();

            expect(karts.length).toBeGreaterThanOrEqual(2);
            expect(karts.some(k => k.id === kart1.id)).toBe(true);
            expect(karts.some(k => k.id === kart2.id)).toBe(true);
        });
    });

    describe('getKart', () => {
        it('should return single kart by ID', async () => {
            const created = await createKart('Test Kart');
            createdKartIds.push(created.id);

            const kart = await getKart(created.id);

            expect(kart).not.toBeNull();
            expect(kart?.id).toBe(created.id);
            expect(kart?.name).toBe('Test Kart');
        });

        it('should return null for non-existent kart', async () => {
            const kart = await getKart('non-existent-id');
            expect(kart).toBeNull();
        });
    });

    describe('updateKart', () => {
        it('should update kart name', async () => {
            const kart = await createKart('Old Name');
            createdKartIds.push(kart.id);

            await updateKart(kart.id, { name: 'New Name' });

            const updated = await getKart(kart.id);
            expect(updated?.name).toBe('New Name');
        });

        it('should update total engine hours', async () => {
            const kart = await createKart('Test Kart');
            createdKartIds.push(kart.id);

            await updateKart(kart.id, { totalEngineHours: 15.5 });

            const updated = await getKart(kart.id);
            expect(updated?.totalEngineHours).toBe(15.5);
        });
    });

    describe('deleteKart - Cascade Delete', () => {
        it('should delete kart and all related data', async () => {
            // Create kart
            const kart = await createKart('Test Kart');
            createdKartIds.push(kart.id);

            // Create related data
            await createSessionLog(kart.id, 60, 'Test session');
            await createTask({
                kartId: kart.id,
                description: 'Test task',
                priority: 'Medium',
                isAutoGenerated: false,
                status: 'pending',
            });
            await createShoppingItem('Test part', kart.id);

            // Delete kart (cascade)
            const result = await deleteKart(kart.id);

            // Verify counts
            expect(result.sessionLogsDeleted).toBe(1);
            expect(result.tasksDeleted).toBe(1);
            expect(result.shoppingItemsDeleted).toBe(1);

            // Verify kart is deleted
            const deletedKart = await getKart(kart.id);
            expect(deletedKart).toBeNull();

            // Remove from cleanup list (already deleted)
            createdKartIds = createdKartIds.filter(id => id !== kart.id);
        });

        it('should handle kart with no related data', async () => {
            const kart = await createKart('Empty Kart');
            createdKartIds.push(kart.id);

            const result = await deleteKart(kart.id);

            expect(result.sessionLogsDeleted).toBe(0);
            expect(result.tasksDeleted).toBe(0);
            expect(result.shoppingItemsDeleted).toBe(0);

            createdKartIds = createdKartIds.filter(id => id !== kart.id);
        });
    });
});
