/**
 * TaskCard Component
 * Feature: 004-maintenance-core
 * 
 * Swipeable task card with priority indicators
 */

'use client';

import React from 'react';
import { SwipeableCard } from '@/components/ui/SwipeableCard';
import type { MaintenanceTask } from '@/types/maintenance';

interface TaskCardProps {
    task: MaintenanceTask;
    onComplete?: () => void;
    onDelete?: () => void;
}

export function TaskCard({ task, onComplete, onDelete }: TaskCardProps) {
    const priorityColors = {
        High: 'border-l-red-600',
        Medium: 'border-l-yellow-600',
    };

    return (
        <SwipeableCard
            onSwipeRight={onComplete}
            onSwipeLeft={onDelete}
            leftColor="green"
            rightColor="red"
        >
            <div className={`border-l-4 ${priorityColors[task.priority]} pl-3`}>
                <div className="flex justify-between items-start">
                    <div className="flex-1">
                        <p className="text-white font-medium">{task.description}</p>
                        {task.isAutoGenerated && (
                            <span className="text-xs text-blue-400">🤖 Auto-generated</span>
                        )}
                    </div>
                    <span className={`text-xs px-2 py-1 rounded ${task.priority === 'High'
                            ? 'bg-red-900 text-red-200'
                            : 'bg-yellow-900 text-yellow-200'
                        }`}>
                        {task.priority}
                    </span>
                </div>
            </div>
        </SwipeableCard>
    );
}
