/**
 * TaskCard Component
 * Feature: 004-maintenance-core
 * 
 * Swipeable task card with priority indicators
 */

'use client';

import React from 'react';
import { SwipeableCard } from '@/components/ui/SwipeableCard';
import type { MaintenanceTask } from '@/types/maintenance';

interface TaskCardProps {
    task: MaintenanceTask;
    onComplete?: () => void;
    onDelete?: () => void;
}

export function TaskCard({ task, onComplete, onDelete }: TaskCardProps) {
    const priorityColors = {
        High: 'border-l-red-600',
        Medium: 'border-l-yellow-600',
        Low: 'border-l-blue-600',
    };

    return (
        <SwipeableCard
            onSwipeRight={onComplete}
            onSwipeLeft={onDelete}
        >
            <div className={`bg-white border border-app-border rounded-lg p-3 shadow-sm border-l-4 ${priorityColors[task.priority]} pl-3`}>
                <div className="flex justify-between items-start">
                    <div className="flex-1">
                        <p className="text-app-text font-medium">{task.description}</p>
                        {task.isAutoGenerated && (
                            <span className="text-xs text-primary">🤖 Auto-generated</span>
                        )}
                    </div>
                    <span className={`text-xs px-2 py-1 rounded font-medium ${task.priority === 'High'
                        ? 'bg-red-100 text-red-800'
                        : 'bg-yellow-100 text-yellow-800'
                        }`}>
                        {task.priority}
                    </span>
                </div>
            </div>
        </SwipeableCard>
    );
}
