/**
 * MaintenanceTask Repository
 * Feature: 004-maintenance-core
 * 
 * Firestore CRUD operations for maintenance tasks with duplicate prevention
 * Refactored for Team Ownership
 */

import {
    collection,
    doc,
    getDocs,
    addDoc,
    updateDoc,
    deleteDoc,
    query,
    where,
    orderBy,
    Timestamp,
    collectionGroup
} from 'firebase/firestore';
import { db } from '../firebase/init';
import type { MaintenanceTask } from '@/types/maintenance';

// Helper for subcollection path
const getTasksCollection = (teamId: string, kartId: string) => 
    collection(db, 'teams', teamId, 'karts', kartId, 'tasks');

/**
 * Get all pending tasks for a kart
 */
export async function getPendingTasks(teamId: string, kartId: string): Promise<MaintenanceTask[]> {
    const tasksQuery = query(
        getTasksCollection(teamId, kartId),
        where('status', '==', 'pending')
    );

    const snapshot = await getDocs(tasksQuery);
    const tasks = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as MaintenanceTask));

    // Sort in memory (or add index for createdAt)
    return tasks.sort((a, b) => b.createdAt.seconds - a.createdAt.seconds);
}

/**
 * Get all tasks for a kart (pending and completed)
 */
export async function getAllTasks(teamId: string, kartId: string): Promise<MaintenanceTask[]> {
    const tasksQuery = query(
        getTasksCollection(teamId, kartId)
    );

    const snapshot = await getDocs(tasksQuery);
    const tasks = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as MaintenanceTask));

    return tasks.sort((a, b) => b.createdAt.seconds - a.createdAt.seconds);
}

/**
 * Get pending task count for a kart
 */
export async function getPendingTaskCount(teamId: string, kartId: string): Promise<number> {
    const tasksQuery = query(
        getTasksCollection(teamId, kartId),
        where('status', '==', 'pending')
    );

    const snapshot = await getDocs(tasksQuery);
    return snapshot.size;
}

/**
 * Check if auto-generated task already exists
 */
export async function autoTaskExists(teamId: string, kartId: string, autoGeneratedType: string): Promise<boolean> {
    const tasksQuery = query(
        getTasksCollection(teamId, kartId),
        where('status', '==', 'pending'),
        where('isAutoGenerated', '==', true),
        where('autoGeneratedType', '==', autoGeneratedType)
    );

    const snapshot = await getDocs(tasksQuery);
    return !snapshot.empty;
}

/**
 * Create maintenance task
 */
export async function createTask(
    teamId: string,
    taskData: Omit<MaintenanceTask, 'id' | 'teamId' | 'createdAt' | 'completedAt' | 'status'>
): Promise<MaintenanceTask> {
    const now = Timestamp.now();

    const task = {
        ...taskData,
        teamId,
        status: 'pending' as const,
        createdAt: now,
    };

    const docRef = await addDoc(getTasksCollection(teamId, taskData.kartId), task);

    return { id: docRef.id, ...task };
}

/**
 * Mark task as completed
 */
export async function completeTask(teamId: string, kartId: string, taskId: string): Promise<void> {
    await updateDoc(doc(db, 'teams', teamId, 'karts', kartId, 'tasks', taskId), {
        status: 'completed',
        completedAt: Timestamp.now(),
    });
}

/**
 * Delete task
 */
export async function deleteTask(teamId: string, kartId: string, taskId: string): Promise<void> {
    await deleteDoc(doc(db, 'teams', teamId, 'karts', kartId, 'tasks', taskId));
}

/**
 * Get all tasks for a TEAM (across all karts)
 * Uses Collection Group Query
 */
export async function getAllTeamTasks(teamId: string): Promise<MaintenanceTask[]> {
    const tasksQuery = query(
        collectionGroup(db, 'tasks'),
        where('teamId', '==', teamId),
        orderBy('createdAt', 'desc')
    );

    const snapshot = await getDocs(tasksQuery);
    return snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as MaintenanceTask));
}
