/**
 * MaintenanceTask Repository
 * Feature: 004-maintenance-core
 * 
 * Firestore CRUD operations for maintenance tasks with duplicate prevention
 */

import {
    collection,
    doc,
    getDocs,
    addDoc,
    updateDoc,
    deleteDoc,
    query,
    where,
    orderBy,
    Timestamp
} from 'firebase/firestore';
import { db, getCurrentUserId } from '../firebase/init';
import type { MaintenanceTask } from '@/types/maintenance';

const TASKS_COLLECTION = 'maintenanceTasks';

/**
 * Get all pending tasks for a kart
 */
/**
 * Get all pending tasks for a kart
 */
export async function getPendingTasks(kartId: string): Promise<MaintenanceTask[]> {
    const userId = getCurrentUserId();
    const tasksQuery = query(
        collection(db, TASKS_COLLECTION),
        where('kartId', '==', kartId),
        where('userId', '==', userId),
        where('status', '==', 'pending')
    );

    const snapshot = await getDocs(tasksQuery);
    const tasks = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as MaintenanceTask));

    // Sort in memory
    return tasks.sort((a, b) => b.createdAt.seconds - a.createdAt.seconds);
}

/**
 * Get all tasks for a kart (pending and completed)
 */
export async function getAllTasks(kartId: string): Promise<MaintenanceTask[]> {
    const userId = getCurrentUserId();
    const tasksQuery = query(
        collection(db, TASKS_COLLECTION),
        where('kartId', '==', kartId),
        where('userId', '==', userId)
    );

    const snapshot = await getDocs(tasksQuery);
    const tasks = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as MaintenanceTask));

    // Sort in memory
    return tasks.sort((a, b) => b.createdAt.seconds - a.createdAt.seconds);
}

/**
 * Get pending task count for a kart
 */
export async function getPendingTaskCount(kartId: string): Promise<number> {
    const userId = getCurrentUserId();
    const tasksQuery = query(
        collection(db, TASKS_COLLECTION),
        where('kartId', '==', kartId),
        where('userId', '==', userId),
        where('status', '==', 'pending')
    );

    const snapshot = await getDocs(tasksQuery);
    return snapshot.size;
}

/**
 * Check if auto-generated task already exists
 * 
 * CRITICAL for duplicate prevention: Query existing pending tasks with same
 * kartId and autoGeneratedType before creating auto-task
 * 
 * @param kartId - Kart ID
 * @param autoGeneratedType - Type of auto-generated task (e.g., "Oil Change")
 * @returns true if task exists, false otherwise
 */
export async function autoTaskExists(kartId: string, autoGeneratedType: string): Promise<boolean> {
    const userId = getCurrentUserId();
    const tasksQuery = query(
        collection(db, TASKS_COLLECTION),
        where('kartId', '==', kartId),
        where('userId', '==', userId),
        where('status', '==', 'pending'),
        where('isAutoGenerated', '==', true),
        where('autoGeneratedType', '==', autoGeneratedType)
    );

    const snapshot = await getDocs(tasksQuery);
    return !snapshot.empty;
}

/**
 * Create maintenance task
 * 
 * @param taskData - Task data (without id)
 * @returns Created task with ID
 */
export async function createTask(taskData: Omit<MaintenanceTask, 'id' | 'createdAt' | 'completedAt'>): Promise<MaintenanceTask> {
    const userId = getCurrentUserId();
    const now = Timestamp.now();

    const task = {
        ...taskData,
        userId,
        status: 'pending' as const,
        createdAt: now,
    };

    const docRef = await addDoc(collection(db, TASKS_COLLECTION), task);

    return { id: docRef.id, ...task };
}

/**
 * Mark task as completed
 */
export async function completeTask(taskId: string): Promise<void> {
    await updateDoc(doc(db, TASKS_COLLECTION, taskId), {
        status: 'completed',
        completedAt: Timestamp.now(),
    });
}

/**
 * Delete task
 */
export async function deleteTask(taskId: string): Promise<void> {
    await deleteDoc(doc(db, TASKS_COLLECTION, taskId));
}

/**
 * Get all tasks for current user (across all karts)
 */
export async function getAllUserTasks(): Promise<MaintenanceTask[]> {
    const userId = getCurrentUserId();
    const tasksQuery = query(
        collection(db, TASKS_COLLECTION),
        where('userId', '==', userId),
        orderBy('createdAt', 'desc')
    );

    const snapshot = await getDocs(tasksQuery);
    return snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as MaintenanceTask));
}
