/**
 * useTasks Hook
 * Feature: 004-maintenance-core
 * 
 * React hook for managing maintenance tasks
 */

'use client';

import { useState, useEffect } from 'react';
import { useAuth } from '@/components/providers/AuthProvider';
import {
    getPendingTasks,
    getAllTasks,
    createTask as createTaskRepo,
    completeTask as completeTaskRepo,
    deleteTask as deleteTaskRepo,
} from '@/lib/firestore/tasks';
import type { MaintenanceTask } from '@/types/maintenance';

interface UseTasksReturn {
    tasks: MaintenanceTask[];
    pendingCount: number;
    loading: boolean;
    error: Error | null;
    refetch: () => Promise<void>;
    createTask: (description: string, priority: 'High' | 'Medium', kartId: string) => Promise<void>;
    completeTask: (taskId: string) => Promise<void>;
    deleteTask: (taskId: string) => Promise<void>;
}

export function useTasks(kartId?: string, showAll = false): UseTasksReturn {
    const { user } = useAuth();
    const [tasks, setTasks] = useState<MaintenanceTask[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<Error | null>(null);

    const fetchTasks = async () => {
        try {
            setLoading(true);
            setError(null);

            const fetchedTasks = kartId
                ? (showAll ? await getAllTasks(kartId) : await getPendingTasks(kartId))
                : [];

            setTasks(fetchedTasks);
        } catch (err) {
            setError(err instanceof Error ? err : new Error('Failed to fetch tasks'));
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchTasks();
    }, [kartId, showAll]);

    const createTask = async (description: string, priority: 'High' | 'Medium', kartIdParam: string) => {
        if (!user) {
            throw new Error('User must be authenticated to create tasks');
        }

        try {
            await createTaskRepo({
                kartId: kartIdParam,
                userId: user.uid,
                description,
                priority,
                isAutoGenerated: false,
                status: 'pending',
            });
            await fetchTasks();
        } catch (err) {
            setError(err instanceof Error ? err : new Error('Failed to create task'));
            throw err;
        }
    };

    const completeTask = async (taskId: string) => {
        try {
            await completeTaskRepo(taskId);
            setTasks(prev => prev.filter(t => t.id !== taskId));
        } catch (err) {
            setError(err instanceof Error ? err : new Error('Failed to complete task'));
            throw err;
        }
    };

    const deleteTask = async (taskId: string) => {
        try {
            await deleteTaskRepo(taskId);
            setTasks(prev => prev.filter(t => t.id !== taskId));
        } catch (err) {
            setError(err instanceof Error ? err : new Error('Failed to delete task'));
            throw err;
        }
    };

    const pendingCount = tasks.filter(t => t.status === 'pending').length;

    return {
        tasks,
        pendingCount,
        loading,
        error,
        refetch: fetchTasks,
        createTask,
        completeTask,
        deleteTask,
    };
}
