/**
 * useTasks Hook
 * Feature: 004-maintenance-core
 * 
 * React hook for managing maintenance tasks
 * Refactored for Team Ownership
 */

'use client';

import { useState, useEffect } from 'react';
import {
    getPendingTasks,
    getAllTasks,
    createTask as createTaskRepo,
    completeTask as completeTaskRepo,
    deleteTask as deleteTaskRepo,
} from '@/lib/firestore/tasks';
import type { MaintenanceTask } from '@/types/maintenance';

interface UseTasksReturn {
    tasks: MaintenanceTask[];
    pendingCount: number;
    loading: boolean;
    error: Error | null;
    refetch: () => Promise<void>;
    createTask: (description: string, priority: 'High' | 'Medium' | 'Low') => Promise<void>;
    completeTask: (taskId: string) => Promise<void>;
    deleteTask: (taskId: string) => Promise<void>;
}

export function useTasks(teamId: string, kartId: string, showAll = false): UseTasksReturn {
    const [tasks, setTasks] = useState<MaintenanceTask[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<Error | null>(null);

    const fetchTasks = async () => {
        if (!teamId || !kartId) return;

        try {
            setLoading(true);
            setError(null);

            const fetchedTasks = showAll 
                ? await getAllTasks(teamId, kartId) 
                : await getPendingTasks(teamId, kartId);

            setTasks(fetchedTasks);
        } catch (err) {
            setError(err instanceof Error ? err : new Error('Failed to fetch tasks'));
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchTasks();
    }, [teamId, kartId, showAll]);

    const createTask = async (description: string, priority: 'High' | 'Medium' | 'Low') => {
        try {
            const newTask = await createTaskRepo(teamId, {
                kartId,
                description,
                priority,
                isAutoGenerated: false,
            });
            // Optimistic update
            setTasks(prev => {
                const updated = [newTask, ...prev];
                return updated.sort((a, b) => b.createdAt.seconds - a.createdAt.seconds);
            });
        } catch (err) {
            setError(err instanceof Error ? err : new Error('Failed to create task'));
            throw err;
        }
    };

    const completeTask = async (taskId: string) => {
        try {
            await completeTaskRepo(teamId, kartId, taskId);
            // Update local state to remove or update status
            if (showAll) {
                 setTasks(prev => prev.map(t => 
                    t.id === taskId ? { ...t, status: 'completed' } : t
                ));
            } else {
                setTasks(prev => prev.filter(t => t.id !== taskId));
            }
        } catch (err) {
            setError(err instanceof Error ? err : new Error('Failed to complete task'));
            throw err;
        }
    };

    const deleteTask = async (taskId: string) => {
        try {
            await deleteTaskRepo(teamId, kartId, taskId);
            setTasks(prev => prev.filter(t => t.id !== taskId));
        } catch (err) {
            setError(err instanceof Error ? err : new Error('Failed to delete task'));
            throw err;
        }
    };

    const pendingCount = tasks.filter(t => t.status === 'pending').length;

    return {
        tasks,
        pendingCount,
        loading,
        error,
        refetch: fetchTasks,
        createTask,
        completeTask,
        deleteTask,
    };
}
