/**
 * Type Definitions and Validation Schemas for Kart Maintenance Core System
 * Feature: 004-maintenance-core
 * 
 * This file contains:
 * - TypeScript interfaces for all entities
 * - Zod validation schemas for runtime type safety
 * - Form input schemas (client-side validation)
 * - API response types
 */

import { z } from 'zod';
import { Timestamp } from 'firebase/firestore';

// ============================================================================
// ENTITY TYPES
// ============================================================================

/**
 * Maintenance threshold configuration for automatic task generation
 */
export interface MaintenanceThreshold {
    type: string;                    // e.g., "Oil Change", "Air Filter", "Valve Adjustment"
    intervalHours: number;           // Baseline interval (e.g., 10 hours)
    yellowWarningHours: number;      // Medium priority trigger (e.g., 8 hours)
    redWarningHours: number;         // High priority trigger (e.g., 10 hours)
    lastCompletedAt?: Timestamp;     // When this maintenance was last completed
}

/**
 * Go-kart entity with engine hours and maintenance configuration
 */
export interface Kart {
    id: string;
    userId: string;
    name: string;                    // e.g., "Kart #17", "Kart #80"
    totalEngineHours: number;        // Computed from session logs
    manualAccessUrl?: string;        // Optional URL to manufacturer's manual
    thresholds: MaintenanceThreshold[];
    createdAt: Timestamp;
    updatedAt: Timestamp;
}

/**
 * Single driving session log entry
 */
export interface SessionLog {
    id: string;
    kartId: string;
    userId: string;
    durationMinutes: number;         // User input
    durationHours: number;           // Computed: durationMinutes / 60
    notes?: string;
    loggedAt: Timestamp;             // When session occurred
    createdAt: Timestamp;            // When log was created
}

/**
 * Maintenance or repair task
 */
export interface MaintenanceTask {
    id: string;
    kartId: string;
    userId: string;
    description: string;
    priority: 'High' | 'Medium' | 'Low';
    status: 'pending' | 'completed';
    isAutoGenerated: boolean;        // true if created by warning zone system
    autoGeneratedType?: string;      // e.g., "Oil Change" (only if auto-generated)
    createdAt: Timestamp;
    completedAt?: Timestamp;
}

/**
 * Part or component to purchase
 */
export interface ShoppingListItem {
    id: string;
    kartId?: string;                 // Optional kart association
    userId: string;
    description: string;
    photoId?: string;                // Reference to IndexedDB photo
    status: 'active' | 'ordered' | 'archived';
    createdAt: Timestamp;
    orderedAt?: Timestamp;
    archivedAt?: Timestamp;
}

/**
 * Compressed photo stored in IndexedDB
 */
export interface Photo {
    id: string;                      // UUID
    blob: Blob;
    originalFileName: string;
    compressedSizeKB: number;
    createdAt: number;               // Unix timestamp
}

// ============================================================================
// VALIDATION SCHEMAS (Zod)
// ============================================================================

/**
 * Maintenance threshold validation
 */
export const maintenanceThresholdSchema = z.object({
    type: z.string().min(1, 'Threshold type required').max(50),
    intervalHours: z.number().positive('Interval must be positive'),
    yellowWarningHours: z.number().positive('Yellow warning must be positive'),
    redWarningHours: z.number().positive('Red warning must be positive'),
    lastCompletedAt: z.instanceof(Timestamp).optional(),
}).refine(
    (data) => data.yellowWarningHours <= data.redWarningHours,
    { message: 'Yellow warning cannot exceed red warning', path: ['yellowWarningHours'] }
).refine(
    (data) => data.redWarningHours <= data.intervalHours,
    { message: 'Red warning cannot exceed interval', path: ['redWarningHours'] }
);

/**
 * Kart validation
 */
export const kartSchema = z.object({
    id: z.string().uuid(),
    userId: z.string().min(1),
    name: z.string().min(1, 'Kart name required').max(50, 'Name too long'),
    totalEngineHours: z.number().nonnegative('Hours cannot be negative'),
    manualAccessUrl: z.string().url('Invalid URL').optional(),
    thresholds: z.array(maintenanceThresholdSchema).min(1, 'At least one threshold required'),
    createdAt: z.instanceof(Timestamp),
    updatedAt: z.instanceof(Timestamp),
});

/**
 * Session log validation
 */
export const sessionLogSchema = z.object({
    id: z.string().uuid(),
    kartId: z.string().min(1, 'Kart ID required'),
    userId: z.string().min(1),
    durationMinutes: z.number()
        .int('Duration must be whole minutes')
        .min(1, 'Duration must be at least 1 minute')
        .max(1440, 'Duration cannot exceed 24 hours'),
    durationHours: z.number().nonnegative(),
    notes: z.string().max(200, 'Notes too long').optional(),
    loggedAt: z.instanceof(Timestamp),
    createdAt: z.instanceof(Timestamp),
});

/**
 * Maintenance task validation
 */
export const maintenanceTaskSchema = z.object({
    id: z.string().uuid(),
    kartId: z.string().min(1),
    userId: z.string().min(1),
    description: z.string().min(1, 'Description required').max(200, 'Description too long'),
    priority: z.enum(['High', 'Medium', 'Low']),
    status: z.enum(['pending', 'completed']),
    isAutoGenerated: z.boolean(),
    autoGeneratedType: z.string().optional(),
    createdAt: z.instanceof(Timestamp),
    completedAt: z.instanceof(Timestamp).optional(),
}).refine(
    (data) => !data.isAutoGenerated || !!data.autoGeneratedType,
    { message: 'Auto-generated tasks must have autoGeneratedType', path: ['autoGeneratedType'] }
);

/**
 * Shopping list item validation
 */
export const shoppingListItemSchema = z.object({
    id: z.string().uuid(),
    kartId: z.string().optional(),
    userId: z.string().min(1),
    description: z.string().min(1, 'Description required').max(200, 'Description too long'),
    photoId: z.string().uuid().optional(),
    status: z.enum(['active', 'ordered', 'archived']),
    createdAt: z.instanceof(Timestamp),
    orderedAt: z.instanceof(Timestamp).optional(),
    archivedAt: z.instanceof(Timestamp).optional(),
});

/**
 * Photo validation (IndexedDB)
 */
export const photoSchema = z.object({
    id: z.string().uuid(),
    blob: z.instanceof(Blob).refine(
        (blob) => blob.size < 512000, // 500KB in bytes
        { message: 'Photo must be less than 500KB' }
    ).refine(
        (blob) => blob.type === 'image/jpeg',
        { message: 'Photo must be JPEG format' }
    ),
    originalFileName: z.string(),
    compressedSizeKB: z.number().positive(),
    createdAt: z.number(),
});

// ============================================================================
// FORM INPUT SCHEMAS (Client-side)
// ============================================================================

/**
 * Kart creation form input
 */
export const createKartInputSchema = z.object({
    name: z.string()
        .min(1, 'Kart name required')
        .max(50, 'Name must be 50 characters or less')
        .trim(),
});

export type CreateKartInput = z.infer<typeof createKartInputSchema>;

/**
 * Session log creation form input
 */
export const createSessionLogInputSchema = z.object({
    kartId: z.string().min(1, 'Kart selection required'),
    durationMinutes: z.number()
        .int('Duration must be whole minutes')
        .min(1, 'Duration must be at least 1 minute')
        .max(1440, 'Cannot exceed 24 hours')
        .or(z.string().transform((val) => parseInt(val, 10))),
    notes: z.string()
        .max(200, 'Notes must be 200 characters or less')
        .optional()
        .or(z.literal('')),
});

export type CreateSessionLogInput = z.infer<typeof createSessionLogInputSchema>;

/**
 * Maintenance task creation form input
 */
export const createMaintenanceTaskInputSchema = z.object({
    kartId: z.string().min(1, 'Kart selection required'),
    description: z.string()
        .min(1, 'Description required')
        .max(200, 'Description must be 200 characters or less')
        .trim(),
    priority: z.enum(['High', 'Medium', 'Low']),
});

export type CreateMaintenanceTaskInput = z.infer<typeof createMaintenanceTaskInputSchema>;

/**
 * Shopping list item creation form input
 */
export const createShoppingListItemInputSchema = z.object({
    description: z.string()
        .min(1, 'Description required')
        .max(200, 'Description must be 200 characters or less')
        .trim(),
    kartId: z.string().optional(),
    photo: z.instanceof(File).optional(),
});

export type CreateShoppingListItemInput = z.infer<typeof createShoppingListItemInputSchema>;

/**
 * Threshold customization form input
 */
export const updateThresholdInputSchema = z.object({
    type: z.string().min(1),
    intervalHours: z.number().positive('Interval must be positive'),
    yellowWarningHours: z.number().positive('Yellow warning must be positive'),
    redWarningHours: z.number().positive('Red warning must be positive'),
}).refine(
    (data) => data.yellowWarningHours <= data.redWarningHours,
    { message: 'Yellow warning cannot exceed red warning', path: ['yellowWarningHours'] }
).refine(
    (data) => data.redWarningHours <= data.intervalHours,
    { message: 'Red warning cannot exceed interval', path: ['redWarningHours'] }
);

export type UpdateThresholdInput = z.infer<typeof updateThresholdInputSchema>;

// ============================================================================
// COMPUTED TYPES (Client-side Display)
// ============================================================================

/**
 * Warning zone evaluation result
 */
export interface WarningZoneStatus {
    thresholdType: string;
    zone: 'green' | 'yellow' | 'red';
    priority: 'High' | 'Medium' | null;
    hoursUntilRed: number;
    hoursUntilYellow: number;
}

/**
 * Kart dashboard display data
 */
export interface KartDashboardStatus {
    kart: Kart;
    pendingTaskCount: number;
    warningZones: WarningZoneStatus[];
    lastSessionDate?: Date;
}

/**
 * Task list item with computed display properties
 */
export interface TaskListItem extends MaintenanceTask {
    kartName: string;               // Denormalized for display
    isOverdue: boolean;             // For auto-generated tasks past red threshold
}

/**
 * Shopping list item with photo blob
 */
export interface ShoppingListItemWithPhoto extends ShoppingListItem {
    photoBlob?: Blob;               // Loaded from IndexedDB
}

// ============================================================================
// DEFAULT VALUES
// ============================================================================

/**
 * Default maintenance thresholds for new karts
 */
export const DEFAULT_MAINTENANCE_THRESHOLDS: Omit<MaintenanceThreshold, 'lastCompletedAt'>[] = [
    {
        type: 'Oil Change',
        intervalHours: 10,
        yellowWarningHours: 8,
        redWarningHours: 10,
    },
    {
        type: 'Air Filter',
        intervalHours: 25,
        yellowWarningHours: 22,
        redWarningHours: 25,
    },
    {
        type: 'Valve Adjustment',
        intervalHours: 50,
        yellowWarningHours: 45,
        redWarningHours: 50,
    },
];

// ============================================================================
// TYPE GUARDS
// ============================================================================

/**
 * Type guard for checking if a task is auto-generated
 */
export function isAutoGeneratedTask(task: MaintenanceTask): task is MaintenanceTask & { autoGeneratedType: string } {
    return task.isAutoGenerated && !!task.autoGeneratedType;
}

/**
 * Type guard for checking if shopping item has photo
 */
export function hasPhoto(item: ShoppingListItem): item is ShoppingListItem & { photoId: string } {
    return !!item.photoId;
}

/**
 * Type guard for checking if shopping item is archived
 */
export function isArchived(item: ShoppingListItem): boolean {
    return item.status === 'archived';
}
