/**
 * Maintenance Engine Service
 * Feature: 004-maintenance-core
 * 
 * Automatic maintenance task generation based on warning zones
 * with duplicate prevention
 */

import type { Kart } from '@/types/maintenance';
import { getWarningZonesNeedingTasks } from './warningZones';
import { autoTaskExists, createTask } from '../firestore/tasks';

/**
 * Check warning zones and create auto-tasks if needed
 * 
 * CRITICAL: This function should be called after every session log creation
 * to trigger automatic task generation when thresholds are crossed
 * 
 * Duplicate Prevention:
 * - Checks for existing pending auto-tasks before creating new ones
 * - Uses autoGeneratedType field to identify task type
 * - Only creates task if no pending task exists for that type
 * 
 * @param kart - Kart with current hours and thresholds
 * @returns Array of created task IDs (empty if no tasks created)
 */
export async function checkAndCreateAutoTasks(kart: Kart): Promise<string[]> {
    const zones = getWarningZonesNeedingTasks(kart);
    const createdTaskIds: string[] = [];

    for (const zone of zones) {
        // Check if auto-task already exists for this threshold type
        const exists = await autoTaskExists(kart.id, zone.thresholdType);

        if (!exists) {
            // Create auto-generated task
            const description = generateTaskDescription(zone.thresholdType, kart.totalEngineHours, zone.zone);

            const task = await createTask({
                kartId: kart.id,
                description,
                priority: zone.priority || 'Medium',
                isAutoGenerated: true,
                autoGeneratedType: zone.thresholdType,
                status: 'pending',
            });

            createdTaskIds.push(task.id);
        }
    }

    return createdTaskIds;
}

/**
 * Generate task description for auto-generated tasks
 * 
 * @param thresholdType - Type of maintenance (e.g., "Oil Change")
 * @param currentHours - Current engine hours
 * @param zone - Warning zone color
 * @returns Human-readable task description
 */
function generateTaskDescription(
    thresholdType: string,
    currentHours: number,
    zone: 'yellow' | 'red'
): string {
    const urgency = zone === 'red' ? 'DUE NOW' : 'approaching';
    return `${thresholdType} ${urgency} (${currentHours.toFixed(1)}h logged)`;
}

/**
 * Bulk check and create auto-tasks for multiple karts
 * 
 * Useful for batch operations or scheduled jobs
 * 
 * @param karts - Array of karts to check
 * @returns Map of kart IDs to created task IDs
 */
export async function checkAndCreateAutoTasksForKarts(
    karts: Kart[]
): Promise<Map<string, string[]>> {
    const results = new Map<string, string[]>();

    for (const kart of karts) {
        const createdIds = await checkAndCreateAutoTasks(kart);
        results.set(kart.id, createdIds);
    }

    return results;
}

/**
 * Get auto-task generation summary for a kart
 * 
 * Useful for debugging and status reporting
 * 
 * @param kart - Kart to analyze
 * @returns Summary of which tasks would be created
 */
export async function getAutoTaskSummary(kart: Kart): Promise<{
    thresholdType: string;
    zone: 'yellow' | 'red';
    taskExists: boolean;
    wouldCreate: boolean;
}[]> {
    const zones = getWarningZonesNeedingTasks(kart);

    const summaries = await Promise.all(
        zones.map(async (zone) => {
            const exists = await autoTaskExists(kart.id, zone.thresholdType);

            return {
                thresholdType: zone.thresholdType,
                zone: zone.zone,
                taskExists: exists,
                wouldCreate: !exists,
            };
        })
    );

    return summaries;
}
