/**
 * Maintenance Engine Unit Tests
 * Feature: 004-maintenance-core
 * 
 * Tests for auto-task generation logic
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { checkAndCreateAutoTasks, getAutoTaskSummary } from '@/lib/services/maintenanceEngine';
import type { Kart } from '@/types/maintenance';
import { Timestamp } from 'firebase/firestore';
import * as tasksRepo from '@/lib/firestore/tasks';

// Mock the tasks repository
vi.mock('@/lib/firestore/tasks', () => ({
    autoTaskExists: vi.fn(),
    createTask: vi.fn(),
}));

describe('Maintenance Engine Auto-Task Generation', () => {
    const createMockKart = (totalEngineHours: number): Kart => ({
        id: 'test-kart-1',
        userId: 'test-user',
        name: 'Test Kart',
        totalEngineHours,
        thresholds: [
            {
                type: 'Oil Change',
                intervalHours: 10,
                yellowWarningHours: 8,
                redWarningHours: 10,
            },
            {
                type: 'Air Filter',
                intervalHours: 25,
                yellowWarningHours: 22,
                redWarningHours: 25,
            }
        ],
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
    });

    beforeEach(() => {
        vi.clearAllMocks();
    });

    describe('checkAndCreateAutoTasks', () => {
        it('should not create tasks when all zones are green', async () => {
            const kart = createMockKart(5); // All zones green

            const createdIds = await checkAndCreateAutoTasks(kart);

            expect(createdIds).toEqual([]);
            expect(tasksRepo.autoTaskExists).not.toHaveBeenCalled();
            expect(tasksRepo.createTask).not.toHaveBeenCalled();
        });

        it('should create task when entering yellow zone and no task exists', async () => {
            const kart = createMockKart(8.5); // Oil Change in yellow

            vi.mocked(tasksRepo.autoTaskExists).mockResolvedValue(false);
            vi.mocked(tasksRepo.createTask).mockResolvedValue({
                id: 'task-1',
                kartId: kart.id,
                userId: kart.userId,
                description: 'Oil Change approaching (8.5h logged)',
                priority: 'Medium',
                status: 'pending',
                isAutoGenerated: true,
                autoGeneratedType: 'Oil Change',
                createdAt: Timestamp.now(),
            });

            const createdIds = await checkAndCreateAutoTasks(kart);

            expect(createdIds).toHaveLength(1);
            expect(tasksRepo.autoTaskExists).toHaveBeenCalledWith(kart.id, 'Oil Change');
            expect(tasksRepo.createTask).toHaveBeenCalledWith(
                expect.objectContaining({
                    kartId: kart.id,
                    priority: 'Medium',
                    isAutoGenerated: true,
                    autoGeneratedType: 'Oil Change',
                })
            );
        });

        it('should create High priority task when entering red zone', async () => {
            const kart = createMockKart(10); // Oil Change in red

            vi.mocked(tasksRepo.autoTaskExists).mockResolvedValue(false);
            vi.mocked(tasksRepo.createTask).mockResolvedValue({
                id: 'task-1',
                kartId: kart.id,
                userId: kart.userId,
                description: 'Oil Change DUE NOW (10.0h logged)',
                priority: 'High',
                status: 'pending',
                isAutoGenerated: true,
                autoGeneratedType: 'Oil Change',
                createdAt: Timestamp.now(),
            });

            const createdIds = await checkAndCreateAutoTasks(kart);

            expect(createdIds).toHaveLength(1);
            expect(tasksRepo.createTask).toHaveBeenCalledWith(
                expect.objectContaining({
                    priority: 'High',
                })
            );
        });

        it('should NOT create duplicate task if one already exists', async () => {
            const kart = createMockKart(10); // Oil Change in red

            vi.mocked(tasksRepo.autoTaskExists).mockResolvedValue(true); // Task exists

            const createdIds = await checkAndCreateAutoTasks(kart);

            expect(createdIds).toEqual([]);
            expect(tasksRepo.autoTaskExists).toHaveBeenCalledWith(kart.id, 'Oil Change');
            expect(tasksRepo.createTask).not.toHaveBeenCalled();
        });

        it('should create tasks for multiple thresholds independently', async () => {
            const kart = createMockKart(23); // Oil Change in red, Air Filter in yellow

            vi.mocked(tasksRepo.autoTaskExists).mockResolvedValue(false);
            vi.mocked(tasksRepo.createTask).mockResolvedValueOnce({
                id: 'task-1',
                kartId: kart.id,
                userId: kart.userId,
                description: 'Oil Change DUE NOW (23.0h logged)',
                priority: 'High',
                status: 'pending',
                isAutoGenerated: true,
                autoGeneratedType: 'Oil Change',
                createdAt: Timestamp.now(),
            }).mockResolvedValueOnce({
                id: 'task-2',
                kartId: kart.id,
                userId: kart.userId,
                description: 'Air Filter approaching (23.0h logged)',
                priority: 'Medium',
                status: 'pending',
                isAutoGenerated: true,
                autoGeneratedType: 'Air Filter',
                createdAt: Timestamp.now(),
            });

            const createdIds = await checkAndCreateAutoTasks(kart);

            expect(createdIds).toHaveLength(2);
            expect(tasksRepo.createTask).toHaveBeenCalledTimes(2);
        });
    });

    describe('getAutoTaskSummary', () => {
        it('should provide summary of what would be created', async () => {
            const kart = createMockKart(8.5); // Oil Change in yellow

            vi.mocked(tasksRepo.autoTaskExists).mockResolvedValue(false);

            const summary = await getAutoTaskSummary(kart);

            expect(summary).toHaveLength(1);
            expect(summary[0]).toEqual({
                thresholdType: 'Oil Change',
                zone: 'yellow',
                taskExists: false,
                wouldCreate: true,
            });
        });

        it('should show existing tasks in summary', async () => {
            const kart = createMockKart(10); // Oil Change in red

            vi.mocked(tasksRepo.autoTaskExists).mockResolvedValue(true);

            const summary = await getAutoTaskSummary(kart);

            expect(summary[0]).toEqual({
                thresholdType: 'Oil Change',
                zone: 'red',
                taskExists: true,
                wouldCreate: false,
            });
        });
    });
});
